; Maps configuration file
; File location: $moddir/addons/amxmodx/configs/maps.ini
; To use with Maps Menu plugin

; Add in your mod's maps here
; Delete this file to use mapcycle.txt

zm_2_crazy_tower2s
zm_2day
zm_2day_int
zm_alfresco_v2
zm_army_in_beta3
zm_assault_gamesites
zm_aztec_infinity
zm_aztec2012_fixed
zm_aztec2012fx
zm_base_humans_final
zm_bk_hideout
zm_c17_old07evening
zm_chakra_gs
zm_corp_3rooms
zm_cpl_egyptian
zm_cpl_mill_kamp
zm_deadly_assault
zm_dust_world_zg
zm_epic_base_v2
zm_five
zm_fortuna
zm_fortuna_v2
zm_fun_world_allstars
zm_iceworld_humans_v2
zm_indungi
zm_industry_beta3
zm_poland_alt
zm_tonga
zm_vendetta
zm_zpv_aztec_infinity_v2
zm_zpv_western_v2
zm_zr_egyptian
