; ----------------------------------
; Zombie Plague 4.3 Extra Items File
; ----------------------------------
; Any changes you make here will be
; automatically loaded at map start

; This file will be automatically updated with new
; editable entries as you install new custom items.

[Chainsaw]
NAME = Chainsaw
COST = 30
TEAMS = HUMAN

[\wVyleceni [ExtraVIP]]
NAME = \wVyleceni [ExtraVIP]
COST = 200
TEAMS = HUMAN

[+2000 HP]
NAME = +2000 HP
COST = 50
TEAMS = ZOMBIE

[Nesmrtelnost [ExtraVIP]]
NAME = Nesmrtelnost [ExtraVIP]
COST = 180
TEAMS = HUMAN

[Terminator [ExtraVIP]]
NAME = Terminator [ExtraVIP]
COST = 200
TEAMS = HUMAN

[Hannibal]
NAME = Hannibal
COST = 350
TEAMS = HUMAN

[ChainSaw \y[v1.0]]
NAME = ChainSaw \y[v1.0]
COST = 15
TEAMS = HUMAN

[MiniGUN!]
NAME = MiniGUN!
COST = 30
TEAMS = HUMAN

[Special Gun [ExtraVIP]]
NAME = Special Gun [ExtraVIP]
COST = 300
TEAMS = HUMAN

[M79 Grenade Launcher]
NAME = M79 Grenade Launcher
COST = 25
TEAMS = HUMAN
