; -------------------------------------
; Zombie Plague 4.3 Zombie Classes File
; -------------------------------------
; Any changes you make here will be
; automatically loaded at map start

; This file will be automatically updated with new
; editable entries as you install new zombie classes.

[Ghost Zombie]
NAME = Ghost Zombie
INFO = [Invisibility E]
MODELS = ch2012_ghost
CLAWMODEL = ch2012_ghost_hand.mdl
HEALTH = 1350
SPEED = 275
GRAVITY = 0.89
KNOCKBACK = 1.00

[Spider Zombie]
NAME = Spider Zombie
INFO = [pavucina]
MODELS = ch2012_spider
CLAWMODEL = ch2012_spider_hand.mdl
HEALTH = 1100
SPEED = 240
GRAVITY = 1.49
KNOCKBACK = 1.00

[Crab Zombie]
NAME = Crab Zombie
INFO = [poskodenie]
MODELS = ch2012_head
CLAWMODEL = ch2012_head_hand.mdl
HEALTH = 600
SPEED = 900
GRAVITY = 0.60
KNOCKBACK = 1.13

[Jump Zombie]
NAME = Jump Zombie
INFO = [vysoke skoky]
MODELS = ch2012_jump
CLAWMODEL = ch2012_jump_hand.mdl
HEALTH = 2100
SPEED = 280
GRAVITY = 0.80
KNOCKBACK = 1.00

[Speed Zombie]
NAME = Speed Zombie
INFO = [speed boost]
MODELS = ch2012_speed
CLAWMODEL = ch2012_speed_hand.mdl
HEALTH = 2100
SPEED = 300
GRAVITY = 1.00
KNOCKBACK = 2.49

[Sleep Zombie]
NAME = Sleep Zombie
INFO = blinding humans
MODELS = ch2012_sleep
CLAWMODEL = ch2012_sleep_hand.mdl
HEALTH = 2000
SPEED = 280
GRAVITY = 0.68
KNOCKBACK = 0.23

[Biger Zombie]
NAME = Biger Zombie
INFO = [hp boost]
MODELS = ch2012_big
CLAWMODEL = ch2012_big_hand.mdl
HEALTH = 2700
SPEED = 250
GRAVITY = 1.00
KNOCKBACK = 1.00
