; - Quick tips -
; * Rename this file to disabled-zplague.ini to turn the mod off
; * Rename it back to plugins-zplague.ini to turn it on
; * Put a semi-colon in front of a plugin to disable it
; * Remove a semi-colon to re-enable a plugin
; * Add the word debug after a plugin to place it in debug mode

; Main plugins
chronic_2012.amxx
zp_custom_weapons.amxx debug

; Custom Buy Menu Weapons
azp_weapon_ak47L.amxx debug

; Extra Items
zp_extra_antidotenade.amxx
zp_extra_mine.amxx
zp_extra_minigun.amxx debug
zp_extra_chainsaw.amxx debug
zp_bazooka_new.amxx
zp_extra_special_gun.amxx
zp_extra_m79.amxx debug
zp_extra_immunity.amxx debug
zp_extra_terminator.amxx
zp_extra_hannibal.amxx
zp_extra_dragon_cannon.amxx debug

; Zombie Extra Item
zp_extra_hp_1000.amxx debug
zp_knockback_bomb_zm.amxx debug

; Zombie classes
zp_c_ghost_zombie.amxx
zp_c_spider_zombie.amxx
zp_c_crab_zombie.amxx
zp_c_jump_zombie.amxx debug
zp_c_speed_zombie.amxx debug
zp_c_biger_zombie.amxx debug
zp_c_sleep_zombie.amxx debug

; Extra Plugins
vip_model_tag.amxx debug
kill_healed.amxx debug
abd.amxx debug
zp_vratbody.amxx
zp_body_rewards.amxx
zp_knife_knockback.amxx debug
zp_parachute.amxx debug
precache_info.amxx
wisetone_camera_menu.amxx

; Add sub-plugins, custom zombie classes, and extra items here
