; ----------------------------------
; Zombie Plague 4.3 Extra Items File
; ----------------------------------
; Any changes you make here will be
; automatically loaded at map start

; This file will be automatically updated with new
; editable entries as you install new custom items.

[Chainsaw]
NAME = Chainsaw
COST = 10
TEAMS = HUMAN

[\wVyleceni [ExtraVIP]]
NAME = \wVyleceni [ExtraVIP]
COST = 200
TEAMS = HUMAN

[+2000 HP]
NAME = Zivot +1000 HP
COST = 40
TEAMS = ZOMBIE

[Nesmrtelnost [ExtraVIP]]
NAME = Nesmrtelnost [ExtraVIP]
COST = 180
TEAMS = HUMAN

[Terminator [ExtraVIP]]
NAME = Terminator [ExtraVIP]
COST = 200
TEAMS = HUMAN

[Hannibal]
NAME = Hannibal
COST = 200
TEAMS = HUMAN

[MiniGUN!]
NAME = MiniGUN [VIP]
COST = 120
TEAMS = HUMAN

[Special Gun [ExtraVIP]]
NAME = Special Gun [ExtraVIP]
COST = 200
TEAMS = HUMAN

[M79 Grenade Launcher]
NAME = M79 Grenade Launcher
COST = 180
TEAMS = HUMAN

[Bazooka [VIP]]
NAME = Bazooka [VIP]
COST = 160
TEAMS = HUMAN

[Dragon Cannon]
NAME = Dragon Cannon
COST = 120
TEAMS = HUMAN

[Bazooka]
NAME = Bazooka
COST = 120
TEAMS = HUMAN

[Tripmine]
NAME = Lasermine plant E
COST = 5
TEAMS = HUMAN
